## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly  
addons:
    apt_packages:
        - gfortran
notifications:
  email: false
git:
  depth: 99999999

before_script: # install dependent unregistered packages
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.add([PackageSpec(url="https://github.com/OpenMendel/SnpArrays.jl.git"), PackageSpec(url="https://github.com/OpenMendel/OrdinalMultinomialModels.jl.git")]);'
after_success:  # TODO: change to after_success once https://github.com/JuliaLang/julia/issues/28306 is fixed
  # push coverage results to Codecov and Coveralls
  - julia -e 'using Pkg, OrdinalGWAS; cd(joinpath(dirname(pathof(OrdinalGWAS)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: osx
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'using OrdinalGWAS; include(joinpath(dirname(pathof(OrdinalGWAS)), "..", "docs", "make.jl"))'
      after_script: skip
      after_success: skip
