## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
addons:
    apt_packages:
        - gfortran
notifications:
  email: false
git:
  depth: 99999999

before_script: # install dependent unregistered packages
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.add([PackageSpec(url="https://github.com/OpenMendel/SnpArrays.jl.git", rev="juliav0.7"), PackageSpec(url="https://github.com/OpenMendel/PolrModels.jl.git", rev="master")]);'
after_script:  # TODO: change to after_success once https://github.com/JuliaLang/julia/issues/28306 is fixed
  # push coverage results to Codecov and Coveralls
  - julia -e 'using Pkg, PolrGWAS; cd(joinpath(dirname(pathof(PolrGWAS)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'
  # # Update the documentation
  # - julia -e 'using Pkg; Pkg.add("Documenter")'
  # - julia -e 'using PolrGWAS; ENV["DOCUMENTER_DEBUG"] = "true"; include(joinpath(dirname(pathof(PolrGWAS)), "..", "docs", "make.jl"))'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: osx
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'include(joinpath(dirname(pathof(PolrGWAS)), "..", "docs", "make.jl"))'
        # - julia --project=docs/ -e 'using Pkg; 
        #                             Pkg.instantiate();
        #                             Pkg.develop(PackageSpec(path=pwd()))'
        # - julia --project=docs/ docs/make.jl
      after_success: skip